//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISPVDemoKlient.IkpWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StavApi", Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice")]
    [System.SerializableAttribute()]
    public partial class StavApi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ISPVDemoKlient.IkpWebService.DostupnostApi DostupnostServeruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZpravaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ISPVDemoKlient.IkpWebService.DostupnostApi DostupnostServeru {
            get {
                return this.DostupnostServeruField;
            }
            set {
                if ((this.DostupnostServeruField.Equals(value) != true)) {
                    this.DostupnostServeruField = value;
                    this.RaisePropertyChanged("DostupnostServeru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Zprava {
            get {
                return this.ZpravaField;
            }
            set {
                if ((object.ReferenceEquals(this.ZpravaField, value) != true)) {
                    this.ZpravaField = value;
                    this.RaisePropertyChanged("Zprava");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DostupnostApi", Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice")]
    public enum DostupnostApi : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        dostupne = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        nedostupnePretizeno = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        nedostupneUdrzba = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        nedostupneTrvale = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IspvChyby", Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice")]
    [System.SerializableAttribute()]
    public partial class IspvChyby : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISPVDemoKlient.IkpWebService.Chyba[] CiselnikChybField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISPVDemoKlient.IkpWebService.ArrayOfInt ChybyEkonomickehoSubjektuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISPVDemoKlient.IkpWebService.Zamestnanec[] ChybyPracovnichPomeruField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ISPVDemoKlient.IkpWebService.Chyba[] CiselnikChyb {
            get {
                return this.CiselnikChybField;
            }
            set {
                if ((object.ReferenceEquals(this.CiselnikChybField, value) != true)) {
                    this.CiselnikChybField = value;
                    this.RaisePropertyChanged("CiselnikChyb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ISPVDemoKlient.IkpWebService.ArrayOfInt ChybyEkonomickehoSubjektu {
            get {
                return this.ChybyEkonomickehoSubjektuField;
            }
            set {
                if ((object.ReferenceEquals(this.ChybyEkonomickehoSubjektuField, value) != true)) {
                    this.ChybyEkonomickehoSubjektuField = value;
                    this.RaisePropertyChanged("ChybyEkonomickehoSubjektu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ISPVDemoKlient.IkpWebService.Zamestnanec[] ChybyPracovnichPomeru {
            get {
                return this.ChybyPracovnichPomeruField;
            }
            set {
                if ((object.ReferenceEquals(this.ChybyPracovnichPomeruField, value) != true)) {
                    this.ChybyPracovnichPomeruField = value;
                    this.RaisePropertyChanged("ChybyPracovnichPomeru");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chyba", Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice")]
    [System.SerializableAttribute()]
    public partial class Chyba : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdChybaField;
        
        private ISPVDemoKlient.IkpWebService.Uroven UrovenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PopisField;
        
        private ISPVDemoKlient.IkpWebService.Veta VetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISPVDemoKlient.IkpWebService.ArrayOfString PolozkyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdChyba {
            get {
                return this.IdChybaField;
            }
            set {
                if ((this.IdChybaField.Equals(value) != true)) {
                    this.IdChybaField = value;
                    this.RaisePropertyChanged("IdChyba");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ISPVDemoKlient.IkpWebService.Uroven Uroven {
            get {
                return this.UrovenField;
            }
            set {
                if ((this.UrovenField.Equals(value) != true)) {
                    this.UrovenField = value;
                    this.RaisePropertyChanged("Uroven");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nazev {
            get {
                return this.NazevField;
            }
            set {
                if ((object.ReferenceEquals(this.NazevField, value) != true)) {
                    this.NazevField = value;
                    this.RaisePropertyChanged("Nazev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Popis {
            get {
                return this.PopisField;
            }
            set {
                if ((object.ReferenceEquals(this.PopisField, value) != true)) {
                    this.PopisField = value;
                    this.RaisePropertyChanged("Popis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public ISPVDemoKlient.IkpWebService.Veta Veta {
            get {
                return this.VetaField;
            }
            set {
                if ((this.VetaField.Equals(value) != true)) {
                    this.VetaField = value;
                    this.RaisePropertyChanged("Veta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ISPVDemoKlient.IkpWebService.ArrayOfString Polozky {
            get {
                return this.PolozkyField;
            }
            set {
                if ((object.ReferenceEquals(this.PolozkyField, value) != true)) {
                    this.PolozkyField = value;
                    this.RaisePropertyChanged("Polozky");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zamestnanec", Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice")]
    [System.SerializableAttribute()]
    public partial class Zamestnanec : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDZAMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISPVDemoKlient.IkpWebService.ArrayOfInt IdChybyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IDZAM {
            get {
                return this.IDZAMField;
            }
            set {
                if ((object.ReferenceEquals(this.IDZAMField, value) != true)) {
                    this.IDZAMField = value;
                    this.RaisePropertyChanged("IDZAM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ISPVDemoKlient.IkpWebService.ArrayOfInt IdChyby {
            get {
                return this.IdChybyField;
            }
            set {
                if ((object.ReferenceEquals(this.IdChybyField, value) != true)) {
                    this.IdChybyField = value;
                    this.RaisePropertyChanged("IdChyby");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Uroven", Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice")]
    public enum Uroven : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Z = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        V = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Veta", Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice")]
    public enum Veta : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MI = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MP = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice", ConfigurationName="IkpWebService.IkpWebServiceSoap")]
    public interface IkpWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name OveritStavApiResult from namespace http://ispv.cz/ikp/webservices/2017-1/ikpwebservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice/OveritStavApi", ReplyAction="*")]
        ISPVDemoKlient.IkpWebService.OveritStavApiResponse OveritStavApi(ISPVDemoKlient.IkpWebService.OveritStavApiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice/OveritStavApi", ReplyAction="*")]
        System.Threading.Tasks.Task<ISPVDemoKlient.IkpWebService.OveritStavApiResponse> OveritStavApiAsync(ISPVDemoKlient.IkpWebService.OveritStavApiRequest request);
        
        // CODEGEN: Generating message contract since element name xmlData from namespace http://ispv.cz/ikp/webservices/2017-1/ikpwebservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice/ZkontrolovatData", ReplyAction="*")]
        ISPVDemoKlient.IkpWebService.ZkontrolovatDataResponse ZkontrolovatData(ISPVDemoKlient.IkpWebService.ZkontrolovatDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice/ZkontrolovatData", ReplyAction="*")]
        System.Threading.Tasks.Task<ISPVDemoKlient.IkpWebService.ZkontrolovatDataResponse> ZkontrolovatDataAsync(ISPVDemoKlient.IkpWebService.ZkontrolovatDataRequest request);
        
        // CODEGEN: Generating message contract since element name xmlData from namespace http://ispv.cz/ikp/webservices/2017-1/ikpwebservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice/OdeslatData", ReplyAction="*")]
        ISPVDemoKlient.IkpWebService.OdeslatDataResponse OdeslatData(ISPVDemoKlient.IkpWebService.OdeslatDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice/OdeslatData", ReplyAction="*")]
        System.Threading.Tasks.Task<ISPVDemoKlient.IkpWebService.OdeslatDataResponse> OdeslatDataAsync(ISPVDemoKlient.IkpWebService.OdeslatDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OveritStavApiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OveritStavApi", Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice", Order=0)]
        public ISPVDemoKlient.IkpWebService.OveritStavApiRequestBody Body;
        
        public OveritStavApiRequest() {
        }
        
        public OveritStavApiRequest(ISPVDemoKlient.IkpWebService.OveritStavApiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class OveritStavApiRequestBody {
        
        public OveritStavApiRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OveritStavApiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OveritStavApiResponse", Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice", Order=0)]
        public ISPVDemoKlient.IkpWebService.OveritStavApiResponseBody Body;
        
        public OveritStavApiResponse() {
        }
        
        public OveritStavApiResponse(ISPVDemoKlient.IkpWebService.OveritStavApiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice")]
    public partial class OveritStavApiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ISPVDemoKlient.IkpWebService.StavApi OveritStavApiResult;
        
        public OveritStavApiResponseBody() {
        }
        
        public OveritStavApiResponseBody(ISPVDemoKlient.IkpWebService.StavApi OveritStavApiResult) {
            this.OveritStavApiResult = OveritStavApiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZkontrolovatDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZkontrolovatData", Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice", Order=0)]
        public ISPVDemoKlient.IkpWebService.ZkontrolovatDataRequestBody Body;
        
        public ZkontrolovatDataRequest() {
        }
        
        public ZkontrolovatDataRequest(ISPVDemoKlient.IkpWebService.ZkontrolovatDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice")]
    public partial class ZkontrolovatDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] xmlData;
        
        public ZkontrolovatDataRequestBody() {
        }
        
        public ZkontrolovatDataRequestBody(byte[] xmlData) {
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZkontrolovatDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZkontrolovatDataResponse", Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice", Order=0)]
        public ISPVDemoKlient.IkpWebService.ZkontrolovatDataResponseBody Body;
        
        public ZkontrolovatDataResponse() {
        }
        
        public ZkontrolovatDataResponse(ISPVDemoKlient.IkpWebService.ZkontrolovatDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice")]
    public partial class ZkontrolovatDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ISPVDemoKlient.IkpWebService.IspvChyby ZkontrolovatDataResult;
        
        public ZkontrolovatDataResponseBody() {
        }
        
        public ZkontrolovatDataResponseBody(ISPVDemoKlient.IkpWebService.IspvChyby ZkontrolovatDataResult) {
            this.ZkontrolovatDataResult = ZkontrolovatDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OdeslatDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OdeslatData", Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice", Order=0)]
        public ISPVDemoKlient.IkpWebService.OdeslatDataRequestBody Body;
        
        public OdeslatDataRequest() {
        }
        
        public OdeslatDataRequest(ISPVDemoKlient.IkpWebService.OdeslatDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice")]
    public partial class OdeslatDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] xmlData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string jmeno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telefon;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string komentar;
        
        public OdeslatDataRequestBody() {
        }
        
        public OdeslatDataRequestBody(byte[] xmlData, string jmeno, string email, string telefon, string komentar) {
            this.xmlData = xmlData;
            this.jmeno = jmeno;
            this.email = email;
            this.telefon = telefon;
            this.komentar = komentar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OdeslatDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OdeslatDataResponse", Namespace="http://ispv.cz/ikp/webservices/2017-1/ikpwebservice", Order=0)]
        public ISPVDemoKlient.IkpWebService.OdeslatDataResponseBody Body;
        
        public OdeslatDataResponse() {
        }
        
        public OdeslatDataResponse(ISPVDemoKlient.IkpWebService.OdeslatDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class OdeslatDataResponseBody {
        
        public OdeslatDataResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IkpWebServiceSoapChannel : ISPVDemoKlient.IkpWebService.IkpWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IkpWebServiceSoapClient : System.ServiceModel.ClientBase<ISPVDemoKlient.IkpWebService.IkpWebServiceSoap>, ISPVDemoKlient.IkpWebService.IkpWebServiceSoap {
        
        public IkpWebServiceSoapClient() {
        }
        
        public IkpWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IkpWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IkpWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IkpWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ISPVDemoKlient.IkpWebService.OveritStavApiResponse ISPVDemoKlient.IkpWebService.IkpWebServiceSoap.OveritStavApi(ISPVDemoKlient.IkpWebService.OveritStavApiRequest request) {
            return base.Channel.OveritStavApi(request);
        }
        
        public ISPVDemoKlient.IkpWebService.StavApi OveritStavApi() {
            ISPVDemoKlient.IkpWebService.OveritStavApiRequest inValue = new ISPVDemoKlient.IkpWebService.OveritStavApiRequest();
            inValue.Body = new ISPVDemoKlient.IkpWebService.OveritStavApiRequestBody();
            ISPVDemoKlient.IkpWebService.OveritStavApiResponse retVal = ((ISPVDemoKlient.IkpWebService.IkpWebServiceSoap)(this)).OveritStavApi(inValue);
            return retVal.Body.OveritStavApiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ISPVDemoKlient.IkpWebService.OveritStavApiResponse> ISPVDemoKlient.IkpWebService.IkpWebServiceSoap.OveritStavApiAsync(ISPVDemoKlient.IkpWebService.OveritStavApiRequest request) {
            return base.Channel.OveritStavApiAsync(request);
        }
        
        public System.Threading.Tasks.Task<ISPVDemoKlient.IkpWebService.OveritStavApiResponse> OveritStavApiAsync() {
            ISPVDemoKlient.IkpWebService.OveritStavApiRequest inValue = new ISPVDemoKlient.IkpWebService.OveritStavApiRequest();
            inValue.Body = new ISPVDemoKlient.IkpWebService.OveritStavApiRequestBody();
            return ((ISPVDemoKlient.IkpWebService.IkpWebServiceSoap)(this)).OveritStavApiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ISPVDemoKlient.IkpWebService.ZkontrolovatDataResponse ISPVDemoKlient.IkpWebService.IkpWebServiceSoap.ZkontrolovatData(ISPVDemoKlient.IkpWebService.ZkontrolovatDataRequest request) {
            return base.Channel.ZkontrolovatData(request);
        }
        
        public ISPVDemoKlient.IkpWebService.IspvChyby ZkontrolovatData(byte[] xmlData) {
            ISPVDemoKlient.IkpWebService.ZkontrolovatDataRequest inValue = new ISPVDemoKlient.IkpWebService.ZkontrolovatDataRequest();
            inValue.Body = new ISPVDemoKlient.IkpWebService.ZkontrolovatDataRequestBody();
            inValue.Body.xmlData = xmlData;
            ISPVDemoKlient.IkpWebService.ZkontrolovatDataResponse retVal = ((ISPVDemoKlient.IkpWebService.IkpWebServiceSoap)(this)).ZkontrolovatData(inValue);
            return retVal.Body.ZkontrolovatDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ISPVDemoKlient.IkpWebService.ZkontrolovatDataResponse> ISPVDemoKlient.IkpWebService.IkpWebServiceSoap.ZkontrolovatDataAsync(ISPVDemoKlient.IkpWebService.ZkontrolovatDataRequest request) {
            return base.Channel.ZkontrolovatDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ISPVDemoKlient.IkpWebService.ZkontrolovatDataResponse> ZkontrolovatDataAsync(byte[] xmlData) {
            ISPVDemoKlient.IkpWebService.ZkontrolovatDataRequest inValue = new ISPVDemoKlient.IkpWebService.ZkontrolovatDataRequest();
            inValue.Body = new ISPVDemoKlient.IkpWebService.ZkontrolovatDataRequestBody();
            inValue.Body.xmlData = xmlData;
            return ((ISPVDemoKlient.IkpWebService.IkpWebServiceSoap)(this)).ZkontrolovatDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ISPVDemoKlient.IkpWebService.OdeslatDataResponse ISPVDemoKlient.IkpWebService.IkpWebServiceSoap.OdeslatData(ISPVDemoKlient.IkpWebService.OdeslatDataRequest request) {
            return base.Channel.OdeslatData(request);
        }
        
        public void OdeslatData(byte[] xmlData, string jmeno, string email, string telefon, string komentar) {
            ISPVDemoKlient.IkpWebService.OdeslatDataRequest inValue = new ISPVDemoKlient.IkpWebService.OdeslatDataRequest();
            inValue.Body = new ISPVDemoKlient.IkpWebService.OdeslatDataRequestBody();
            inValue.Body.xmlData = xmlData;
            inValue.Body.jmeno = jmeno;
            inValue.Body.email = email;
            inValue.Body.telefon = telefon;
            inValue.Body.komentar = komentar;
            ISPVDemoKlient.IkpWebService.OdeslatDataResponse retVal = ((ISPVDemoKlient.IkpWebService.IkpWebServiceSoap)(this)).OdeslatData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ISPVDemoKlient.IkpWebService.OdeslatDataResponse> ISPVDemoKlient.IkpWebService.IkpWebServiceSoap.OdeslatDataAsync(ISPVDemoKlient.IkpWebService.OdeslatDataRequest request) {
            return base.Channel.OdeslatDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ISPVDemoKlient.IkpWebService.OdeslatDataResponse> OdeslatDataAsync(byte[] xmlData, string jmeno, string email, string telefon, string komentar) {
            ISPVDemoKlient.IkpWebService.OdeslatDataRequest inValue = new ISPVDemoKlient.IkpWebService.OdeslatDataRequest();
            inValue.Body = new ISPVDemoKlient.IkpWebService.OdeslatDataRequestBody();
            inValue.Body.xmlData = xmlData;
            inValue.Body.jmeno = jmeno;
            inValue.Body.email = email;
            inValue.Body.telefon = telefon;
            inValue.Body.komentar = komentar;
            return ((ISPVDemoKlient.IkpWebService.IkpWebServiceSoap)(this)).OdeslatDataAsync(inValue);
        }
    }
}
